export const INSIGHT_VALIDATION_ISSUE_CODES = [
  'INSIGHT_VALIDATION_INVALID_STRUCTURE',
  'INSIGHT_VALIDATION_DUPLICATE_ID',
  'INSIGHT_VALIDATION_DUPLICATE_REFERENCE',
  'INSIGHT_VALIDATION_INVALID_EVIDENCE',
  'INSIGHT_VALIDATION_INVALID_CONFIDENCE',
  'INSIGHT_VALIDATION_RULE_REFERENCE_NOT_FOUND',
  'INSIGHT_VALIDATION_INCOMPATIBLE_VERSION',
  'INSIGHT_VALIDATION_INVALID_CATEGORY',
  'INSIGHT_VALIDATION_INVALID_SCOPE',
  'INSIGHT_VALIDATION_INVALID_STATUS',
  'INSIGHT_VALIDATION_INVALID_SEVERITY',
  'INSIGHT_VALIDATION_INTERNAL_INCONSISTENCY',
  'INSIGHT_VALIDATION_FAIL_CLOSED',
] as const

export type ValidationIssueCode = (typeof INSIGHT_VALIDATION_ISSUE_CODES)[number]

export interface ValidationIssue {
  readonly code: ValidationIssueCode
  readonly path: string
  readonly message: string
}